/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ql_sanpham.view;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ql_sanpham.bussiness.Human_function;
import ql_sanpham.entity.Human;

/**
 *
 * @author LaptopAZ.vn
 */
public class Frm_QuanLiNguoiDung extends javax.swing.JFrame {
    Human_function human_function = new Human_function();
    DefaultTableModel defaultTableModel = null;
    List<Human> listHuman;
    Human humanSelected = null;

    /**
     * Creates new form Frm_QuanLiNguoiDung
     */
    public Frm_QuanLiNguoiDung() {
        initComponents();
        loadDataToJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHuman = new javax.swing.JTable();
        btnNewHuman = new javax.swing.JButton();
        btnSaveHuman = new javax.swing.JButton();
        btnUpdateHuman = new javax.swing.JButton();
        btnDeleteHuman = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTenNguoiDangKi = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edtTenNguoiDangKi = new javax.swing.JTextField();
        txtCmnd = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        edtCmnd = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edtDiaChi = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edtDienThoai = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edtQueQuan = new javax.swing.JTextField();
        edtCongViec = new javax.swing.JTextField();
        txtCongViec = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edtNoiLamViẹc = new javax.swing.JTextField();
        txtNoiLamViec = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTaoChuyenTrang = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblHuman.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblHuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHumanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHuman);
        tblHuman.getAccessibleContext().setAccessibleName("");
        tblHuman.getAccessibleContext().setAccessibleDescription("");

        btnNewHuman.setIcon(new javax.swing.ImageIcon("E:\\XAMPP\\Netbeans\\Project\\16.2_QuanLiSanPham\\Upload_Image\\load.png")); // NOI18N
        btnNewHuman.setText("Mới");
        btnNewHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewHumanActionPerformed(evt);
            }
        });

        btnSaveHuman.setIcon(new javax.swing.ImageIcon("E:\\XAMPP\\Netbeans\\Project\\16.2_QuanLiSanPham\\Upload_Image\\add.png")); // NOI18N
        btnSaveHuman.setText("Lưu");
        btnSaveHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHumanActionPerformed(evt);
            }
        });

        btnUpdateHuman.setIcon(new javax.swing.ImageIcon("E:\\XAMPP\\Netbeans\\Project\\16.2_QuanLiSanPham\\Upload_Image\\update.png")); // NOI18N
        btnUpdateHuman.setText("Sửa");
        btnUpdateHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHumanActionPerformed(evt);
            }
        });

        btnDeleteHuman.setIcon(new javax.swing.ImageIcon("E:\\XAMPP\\Netbeans\\Project\\16.2_QuanLiSanPham\\Upload_Image\\delete.png")); // NOI18N
        btnDeleteHuman.setText("Xóa");
        btnDeleteHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHumanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(btnNewHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewHuman)
                    .addComponent(btnSaveHuman)
                    .addComponent(btnUpdateHuman)
                    .addComponent(btnDeleteHuman))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTenNguoiDangKi.setText("Tên người đăng kí");

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("(*)");

        txtCmnd.setText("Chứng minh nhân dân");

        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("(*)");

        txtDiaChi.setText("Địa chỉ");

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("(*)");

        txtDienThoai.setText("Điện thoại");

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("(*)");

        txtEmail.setText("Email");

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("(*)");

        txtQueQuan.setText("Quê quán");

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("(*)");

        edtQueQuan.setToolTipText("");

        txtCongViec.setText("Công việc");

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("(*)");

        txtNoiLamViec.setText("Nơi làm việc");

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("(*)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtDiaChi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)
                                    .addGap(87, 87, 87))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtCmnd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDienThoai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtQueQuan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCongViec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNoiLamViec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTenNguoiDangKi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtTenNguoiDangKi, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(edtDienThoai)
                    .addComponent(edtEmail)
                    .addComponent(edtCongViec)
                    .addComponent(edtNoiLamViẹc)
                    .addComponent(edtCmnd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edtQueQuan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNguoiDangKi)
                            .addComponent(jLabel16))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(edtTenNguoiDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCmnd)
                    .addComponent(jLabel15)
                    .addComponent(edtCmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi)
                    .addComponent(jLabel14)
                    .addComponent(edtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDienThoai)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQueQuan)
                    .addComponent(jLabel12)
                    .addComponent(edtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCongViec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCongViec)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNoiLamViẹc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiLamViec)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTaoChuyenTrang.setText("Tạo");
        btnTaoChuyenTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoChuyenTrangActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon("E:\\XAMPP\\Netbeans\\Project\\16.2_QuanLiSanPham\\Upload_Image\\back.png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Quản lý người đăng kí");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Thông tin người đăng kí");

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Danh sách người đăng kí");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaoChuyenTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnTaoChuyenTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewHumanActionPerformed
        // TODO add your handling code here:
        edtTenNguoiDangKi.setText("");
        edtCmnd.setText("");
        edtDiaChi.setText("");
        edtDienThoai.setText("");
        edtEmail.setText("");
        edtQueQuan.setText("");
        edtCongViec.setText("");  
        edtNoiLamViẹc.setText("");
    }//GEN-LAST:event_btnNewHumanActionPerformed

    private void btnSaveHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHumanActionPerformed
        // TODO add your handling code here:
        String name = edtTenNguoiDangKi.getText().trim();
        String cmnd = edtCmnd.getText().trim();
        String address = edtDiaChi.getText().trim();
        String telephone = edtDienThoai.getText().trim();
        String email = edtEmail.getText().trim();
        String country = edtQueQuan.getText().trim();
        String job = edtCongViec.getText().trim();
        String workplace = edtNoiLamViẹc.getText().trim();
        if(name.equals("") 
                || String.valueOf(cmnd).equals("") 
                || address.equals("") 
                || String.valueOf(telephone).equals("") 
                || email.equals("") 
                || country.equals("") 
                || job.equals("") 
                || workplace.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập đầy đủ thông tin !!!");
        }else{
            int idHuman = human_function.insert(new Human(0, name, cmnd, address, telephone, email, country, job, workplace));
            if(idHuman >= 0){
                JOptionPane.showMessageDialog(rootPane, "Thêm mới thành công");
                loadDataToJTable();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Thêm mới thất bại");
            }
        }
            
    }//GEN-LAST:event_btnSaveHumanActionPerformed

    private void btnUpdateHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHumanActionPerformed
        // TODO add your handling code here:
        String name = edtTenNguoiDangKi.getText().trim();
        String cmnd = edtCmnd.getText().trim();
        String address = edtDiaChi.getText().trim();
        String telephone = edtDienThoai.getText().trim();
        String email = edtEmail.getText().trim();
        String country = edtQueQuan.getText().trim();
        String job = edtCongViec.getText().trim();
        String workplace = edtNoiLamViẹc.getText().trim();
        if(name.equals("") 
//                || String.valueOf(cmnd).equals("") 
                || address.equals("") 
//                || String.valueOf(telephone).equals("") 
                || email.equals("") 
                || country.equals("") 
                || job.equals("") 
                || workplace.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập đầy đủ thông tin !!!");
        }else{
            boolean isUpdate = human_function.update(new Human(humanSelected.getIdHuman(), name, cmnd, address, telephone, email, country, job, workplace));
            if(isUpdate){
                JOptionPane.showMessageDialog(rootPane, "Sửa mới thành công");
                loadDataToJTable();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sửa thất bại, mời bạn thử lại");
            }
        }
        
    }//GEN-LAST:event_btnUpdateHumanActionPerformed

    private void btnDeleteHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHumanActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Bạn thật sự muốn xóa ( ͡° ͜ʖ ͡°) ?", "Cảnh báo xóa !!", JOptionPane.YES_NO_OPTION) != 0) {
        } else {
            boolean isDelete = human_function.delete(humanSelected);
            if (isDelete) {
                // gọi hàm delete
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                // thêm vào table
                loadDataToJTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xóa thất bại!!!!");
            }
        }
    }//GEN-LAST:event_btnDeleteHumanActionPerformed

    private void btnTaoChuyenTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoChuyenTrangActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Frm_QuanLiSanPham().setVisible(true);
    }//GEN-LAST:event_btnTaoChuyenTrangActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Frm_TrangChu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblHumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHumanMouseClicked
        // TODO add your handling code here:
        int rowSelected = tblHuman.getSelectedRow();
        humanSelected = listHuman.get(rowSelected);
        edtTenNguoiDangKi.setText(humanSelected.getName());
        edtCmnd.setText(humanSelected.getCmnd());
        edtDiaChi.setText(humanSelected.getAddress());
        edtDienThoai.setText(humanSelected.getTelephone());
        edtEmail.setText(humanSelected.getEmail());
        edtQueQuan.setText(humanSelected.getCountry());
        edtCongViec.setText(humanSelected.getJob());
        edtNoiLamViẹc.setText(humanSelected.getWorkplace());
    }//GEN-LAST:event_tblHumanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLiNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_QuanLiNguoiDung().setDefaultCloseOperation(EXIT_ON_CLOSE);
                new Frm_QuanLiNguoiDung().setSize(700,600);
                new Frm_QuanLiNguoiDung().setMinimumSize(new Dimension(700,0));
                new Frm_QuanLiNguoiDung().setMaximumSize(new Dimension(600, Integer.MAX_VALUE));
                new Frm_QuanLiNguoiDung().setVisible(true);
            }
        });
    }
    
    private void loadDataToJTable() {
        defaultTableModel = new DefaultTableModel();
        Object[] columnTitle = {"Tên", "Cmnd", "Địa chỉ", "Điện thoại", "Email", "Quê quán", "Công việc", "Nơi làm việc"};
        defaultTableModel.setColumnIdentifiers(columnTitle);
        listHuman = human_function.getAll();
        Object[] rowData = null;
//        String nameCategory = "";
        for (Human human : listHuman) {
//            nameCategory = category_function.get(product.getCategoryid()).get().getName();
            rowData = new Object[]{human.getName()
                    , human.getCmnd()
                    , human.getAddress()
                    , human.getTelephone()
                    , human.getEmail()
                    , human.getCountry()
                    , human.getJob()
                    , human.getWorkplace()};
            defaultTableModel.addRow(rowData);
        }
        tblHuman.setModel(defaultTableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteHuman;
    private javax.swing.JButton btnNewHuman;
    private javax.swing.JButton btnSaveHuman;
    private javax.swing.JButton btnTaoChuyenTrang;
    private javax.swing.JButton btnUpdateHuman;
    private javax.swing.JTextField edtCmnd;
    private javax.swing.JTextField edtCongViec;
    private javax.swing.JTextField edtDiaChi;
    private javax.swing.JTextField edtDienThoai;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNoiLamViẹc;
    private javax.swing.JTextField edtQueQuan;
    private javax.swing.JTextField edtTenNguoiDangKi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHuman;
    private javax.swing.JLabel txtCmnd;
    private javax.swing.JLabel txtCongViec;
    private javax.swing.JLabel txtDiaChi;
    private javax.swing.JLabel txtDienThoai;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNoiLamViec;
    private javax.swing.JLabel txtQueQuan;
    private javax.swing.JLabel txtTenNguoiDangKi;
    // End of variables declaration//GEN-END:variables
}

